# action.yml
name: 'Build E2A TARP'
description: 'Deploy offline Electron version of E2A TARP'
inputs:
  gh_token:  # id of input
    description: 'GitHub token for the E2A user'
    required: true
    default: ''
  gh_username:
    description: 'GitHub username for the E2A user'
    required: true
    default: ''
  gh_repo:
    description: 'GitHub repo name'
    required: true
    default: 'E2A/e2a-cip'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh_username }}
    - ${{ inputs.gh_token }}
    - ${{ inputs.gh_repo }}